name: GitHub → Slack Notifier

on:
  issues:
    types: [opened, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, merged, review_requested]
  issue_comment:
    types: [created]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Slack Notification
        uses: marksman-20/teamwok-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

